### ISSUE TITLE
Плохо залитый проект.

### ISSUE THREAD

**Issue by java8compiler** [MoonlightOwl/O-Blocks#1]
Залей нормально проект, я задолбался колупатся в нём, и ванговать как ты его устроил.

**Comment by MoonlightOwl** [comment]
Итак, все проблемы решились. Кривизна, как и следовало ожидать, таилась вовсе не в проекте ;)

**Comment by MoonlightOwl** [comment]
Ну будущее: клонируя проект, не забывайте настроить папку с ресурсами (/src/resources), и подключить к проекту библиотеку в папке /lib.
