### ISSUE TITLE
Отладка.

### ISSUE THREAD

**Issue by java8compiler** [MoonlightOwl/O-Blocks#2]
Предлагаю добавить отладочный режим, мы передаём в аргумент программе логическое значение, и на основании его она будет производить вывод исключение, если значение равно true stacktrace выводится в консоль, если равно false(Значение по умолчанию)Он будет сохранять в папку Errors, с именем файла текущего время.

**Comment by MoonlightOwl** [comment]
На данный момент все возникающие ошибки выводятся в консоль (если программа была запущена через нее), а также дублируются всплывающими окнами с описанием ошибки и стактрейсом.
Ты предлагаешь, по сути, добавить опциональное логирование в файл для класса Log. Думаю, это можно будет организовать. И если не сейчас, то на тот момент, когда количество и подробность логируемой информации, необходимой для локализации ошибки превысят один стактрейс :)
